### ISSUE TITLE
Any plans to release the PDMB dataset?

### ISSUE THREAD

**Issue by jin-s13** [FeixiangZhou/GM-SCENet#1]
I plan to integrate the PDMB dataset in [MMPose](https://github.com/open-mmlab/mmpose), an open-source toolbox for pose estimation related tasks.

Do you have any plans to release the PDMB dataset?

**Comment by FeixiangZhou** [comment]
> I plan to integrate the PDMB dataset in [MMPose](https://github.com/open-mmlab/mmpose), an open-source toolbox for pose estimation related tasks.
> 
> Do you have any plans to release the PDMB dataset?



Thank you for your interest in our work. We will release our dataset and codes as soon as possible. Then you can integrate our PDMB dataset into your great project MMPose.
