### ISSUE TITLE
Not found data_load_RGB_multiscale, AttentionCRFmodel.mainStackedHourGlass_full_finalcas2_C3GM2 

### ISSUE THREAD

**Issue by AdamGloria** [FeixiangZhou/GM-SCENet#3]
Hello, I am very sorry to disturb you. While checking the train.py file, I found that the statements importing library functions from data_load_RGB_multiscale import MouseKeypointsDataset and from AttentionCRFmodel.mainStackedHourGlass_full_ finalcas2_C3GM2 import * the data_load_RGB_multiscale, AttentionCRFmodel.mainStackedHourGlass_full_finalcas2_C3GM2 are not found in the file, can the author provide it?

**Comment by FeixiangZhou** [comment]
> Hello, I am very sorry to disturb you. While checking the train.py file, I found that the statements importing library functions from data_load_RGB_multiscale import MouseKeypointsDataset and from AttentionCRFmodel.mainStackedHourGlass_full_ finalcas2_C3GM2 import * the data_load_RGB_multiscale, AttentionCRFmodel.mainStackedHourGlass_full_finalcas2_C3GM2 are not found in the file, can the author provide it?

Thank you for your comment. We have changed it to `from model.mainStackedHourGlass_full_finalcas2_C3GM2 import *`
The data_load_RGB_multiscale.py has been uploaded.
